name: C++ CI

on:
  push:
    branches:
      - main  # Modifiez en fonction de votre branche

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev  # Installez Google Test

      - name: Build Google Test
        run: |
          sudo apt-get install -y cmake  # Assurez-vous que CMake est installé
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp ./lib/* /usr/lib  # Copiez les bibliothèques compilées

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: build/test_out  # Remplacez par le chemin correct de votre exécutable

